### ISSUE TITLE
Yurt incorrectly referencing dependent components as :not-started within go-loops

### ISSUE THREAD

**Issue by dhruvbhatia** [tolitius/yurt#1]
Firstly great work on both mount and yurt - they're both awesome projects. 🎯 

I ran into a weird edge case with `yurt` that doesn't happen in `mount`.

When `componentB` relies on `componentA`, the value of `componentA` will incorrectly return _:not-started_ when it is referenced within a go-loop.

E.g. let's say `componentB` sets up a go-loop and wants to reference `componentA` whenever it receives a message to a channel as per below:

``` clojure
; ... somewhere in componentB.clj's mount start function
; ...

(println componentA) ; correctly prints the started value of componentA, a dependent component

  (async/go-loop []
    (when-let [msg (async/<! c)]
      (println "received msg" msg)
      (println componentA) ; <----- this incorrectly prints :not-started under yurt
      (recur)))
```

Note how within the go-loop itself, the started value of `componentA` does not print as intended, but instead gives _:not-started_.

As above, this only happens when loading a system through yurt; vanilla mount handles the situation correctly and prints the value of `componentA` as expected.

**Comment by tolitius** [comment]
interesting, thanks for reporting it.

I believe this could be cause by the incorrect order of starting things. for example from the code above there are actually 3 states:
- `componentA`
- `componentB`
- go channel `c`

Since `go-loop` is a macro, it expands into looking for a `componentA` _var_ rather than a value. This is most probably the reason why you see `:not-started`. This would not be a problem with mount, since this var would still be there after `(mount/start)`, but yurt does not keep vars around.

One way to do it with yurt would be to treat a componentA as a _value_, i.e.

``` clojure
(defn create-go-loop [c A]
  (async/go-loop []
    (when-let [msg (async/<! c)]
      (println "received msg" msg)
      (println A)
      (recur))))
```

This way a macro would expand into using a _value_ that can still be passed in.

The yurt's sample app [does something very similar](https://github.com/tolitius/yurt/blob/master/dev/clj/neo/www.clj#L20) when working with Compojure's `defroutes` which is a macro.

**Comment by dhruvbhatia** [comment]
Thanks for the detailed explanation - that clears it up for me!

I can confirm that your workaround of explicitly passing in the _value_ of each component I need to access within a macro solves the issue.

Is it theoretically possible for yurt to do this automatically whenever it encounters a macro? That way code built for `mount` can be used with `yurt` without any modifications needed.

That said, totally satisfied with your solution, so feel free to close this issue if desired! 👍

**Comment by tolitius** [comment]
theoretically possible :)

but I'd like to keep `yurt` minimal. I agree, understanding that you work with a `value` rather than with a `reference` is _important_. I might need to improve docs to explain gotchas with macros.
